name: LiquipEnhancements
main: io.github.liquip.enhancements.LiquipEnhancements
version: ${version}
api-version: '1.20'
dependencies:
  server:
    Liquip:
      load: BEFORE
      required: true
      join-classpath: true