name: LiquipEnhancements
main: io.github.liquip.enhancements.LiquipEnhancements
version: 0.1.0-alpha
api-version: 1.19
dependencies:
  - name: Liquip
    required: true
    bootstrap: false
load-before:
  - name: Liquip
    bootstrap: false